package com.bukkeubook.book.document.model.dto;

public class test {
//	EMP_NO	NUMBER
//	EMP_NAME	NVARCHAR2(31 CHAR)
//	EMP_PHONE_1	VARCHAR2(10 BYTE)
//	EMP_PHONE_2	VARCHAR2(10 BYTE)
//	EMP_PHONE_3	VARCHAR2(10 BYTE)
//	EMP_BIRTH	DATE
//	EMP_GENDER	VARCHAR2(15 BYTE)
//	EMP_EMAIL	VARCHAR2(63 BYTE)
//	EMP_JOB_CODE	NVARCHAR2(31 CHAR)
//	EMP_ADDRESS	NVARCHAR2(255 CHAR)
//	EMP_D_ADDRESS	NVARCHAR2(255 CHAR)
//	EMP_ENT_DATE	DATE
//	EMP_END_DATE	DATE
//	EMP_END_YN	VARCHAR2(3 BYTE)
//	EMP_PWD	VARCHAR2(255 BYTE)
//	DEPT_CODE	NUMBER
	
	private int empNo;
	private String empName;
	private String empPhone1;
	private String empPhone2;
	private String empPhone3;
	
}
